export SWARM_NET="test_net"
export DOCKER_IMAGE="nmmorais/cyclon_tman"
export IPS_FILE="config/ips_file.txt"
export LATENCY_MAP="config/lats_file.txt"
export SWARM_VOL="/tmp/CyclonTMan"
export SWARM_SUBNET="10.10.0.0/16"